### ISSUE TITLE
Excellent repo

### ISSUE THREAD

**Issue by trophywtf** [ml58158/SCCM-Client-Dynamic-Provisioning#1]
Hello. This is not really a bug. I found your git repo on client provisioning to be extremely helpful and thus I would like to buy you a beer. I was unsure how to get a hold of you so I created this "issue". Sorry if it messes up some statistics or anything like that. Anywho, if you have a paypal or some way of donating some money for a beer please let me know. Have a good one good fellow.

**Comment by ml58158** [comment]
I am glad that you found it extremely helpful .

If you want to donate , you send PayPal to here :
Mattlarkin@charter.net .

Sent from my iPhone

On Sep 21, 2018, at 4:35 AM, trophywtf <notifications@github.com> wrote:

Hello. This is not really a bug. I found your git repo on client provisioning to be extremely helpful and thus I would like to buy you a beer. I was unsure how to get a hold of you so I created this "issue". Sorry if it messes up some statistics or anything like that. Anywho, if you have a paypal or some way of donating some money for a beer please let me know. Have a good one good fellow.
