### ISSUE TITLE
AddLocalMachineToCollection.ps1

### ISSUE THREAD

**Issue by AgetroNairb** [ml58158/SCCM-Client-Dynamic-Provisioning#2]
Can you provide a copy of your AddLocalMachineToCollection.ps1 file? I'm having issues getting that part to work correctly.

Thanks!

**Comment by ml58158** [comment]
I added the file to the repo for you.

I use a web service to pull the local machine name and drop it into the collection.
You may have another method to do it, though.

The basic premise is that it creates a scheduled task to open Chrome at login , pass the machine name as an argument and add it to the collection via a powershell file on the server.

**Comment by AgetroNairb** [comment]
Great, thanks! I'm testing a similar process using [ConfigMgrWebService](https://github.com/NickolajA/ConfigMgrWebService) and [PSAppDeployToolkit](https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/releases). I just found my problem where I forgot to escape the computer name environment variable so it's used correctly when the task is run and not when it's created. Now I have to either figure out why the scheduled task isn't unregistering or move the unregister to the task sequence.

```
$ScheduledTaskAction = 
    New-ScheduledTaskAction `
        -Execute "Powershell.exe" `
        -Argument "-NoProfile -WindowStyle Hidden -Command `"& { `$AddToCollection = (New-WebServiceProxy -Uri 'http://sccmserver/ConfigMgrWebService/CMCollections.asmx').AddToCollection(`$env:COMPUTERNAME, 'Win10 - new builds', 'SecretKey'); if (`$AddToCollection -eq 'true') { Unregister-ScheduledTask -TaskName 'AddToCollection' -Confirm:`$false } }`""

$ScheduledTaskTrigger = 
    New-ScheduledTaskTrigger `
        -AtLogOn

Register-ScheduledTask `
    -Action $ScheduledTaskAction `
    -Trigger $ScheduledTaskTrigger `
    -TaskName "AddToCollection" `
    -Description "Windows 10 new build - add to collection"

Execute-Process -Path "$dirFiles\ccmsetup.exe" -Parameters "/NoService SMSCACHESIZE=10240 SMSSITECODE=AUTO" -WindowStyle "Hidden"
```

**Comment by ml58158** [comment]
I think you missed the first part.

You need to make the ppkg first and include the ccmsetup files in that.

You can't add the machine to a collection until sccm is fully installed and configured first.

**Comment by ml58158** [comment]
Go through Parts A,B and C first.

**Comment by AgetroNairb** [comment]
Yeah, I got that part. I'm using the PSAppDeployToolkit to script creating the scheduled task and install the SCCM client. I wrap the PSAppDeployToolkit files with the SCCM client install files using 7-Zip into a self-extracting EXE and put this into the PPKG. The PPKG runs the EXE, which extracts and runs Deploy-Application.exe to create the scheduled task and install the SCCM client. After the first logon, the SCCM client is already installed and the scheduled task runs (now that I fixed the script error with the computer name). It seems to be working now. I just need to add the task sequence part.

**Comment by ml58158** [comment]
Here's my current PPKG Version.

set LOGFILE=%SystemDrive%\Windows\Logs\install_sccm_client.log
set curTimestamp=%date:~7,2%_%date:~3,3%_%date:~10,4%_%time:~0,2%_%time:~3,2%
echo Provisioning Starting Time: %curTimestamp% >> %LOGFILE%
echo Creating Logs Folder >> %LOGFILE%
mkdir C:\Logs >> %LOGFILE%
echo Expanding sccmclient.cab >> %LOGFILE%
expand -r sccmclient.cab -F:* . >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%
echo Installing SCCM Client Software >> %LOGFILE%
Ccmsetup.exe >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%

echo Installing Google Chrome
googlechromestandaloneenterprise64.msi /qn >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%

echo Copying Start Menu Configuration >> %LOGFILE%
copy DefaultLayouts.xml C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\StartMenu.xml >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%
copy LayoutModification.xml C:\Users\Default\AppData\Local\Microsoft\Windows\Shell\LayoutModification.xml >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%
 
echo Copying AutoLogin reg to Logs folder >> %LOGFILE%
copy autologin-svcsccmprov.reg C:\Logs\autologin-svcsccmprov.reg >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%

echo Creating Scheduled Task >> %LOGFILE%
powershell.exe -ExecutionPolicy Bypass -NoLogo -NonInteractive -File AddLocalMachineToCollection.ps1 >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%

echo Adding AutoLogin to local test account >> %LOGFILE%
regedit.exe /S autologin-svcsccmprov.reg >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%

echo Running GP Update >> %LOGFILE%
gpupdate /force >> %LOGFILE%
echo result: %ERRORLEVEL% >> %LOGFILE%

echo Provisioning Completed at:%curTimestamp%  >> %LOGFILE%

**Comment by ml58158** [comment]
This bat file along with the installer files are compressed into a .CAB file and that CAB file goes into the PPKG .

**Comment by AgetroNairb** [comment]
Yeah, I'm essentially doing the same thing. I just decided to use the PSAppDeployToolkit with PowerShell instead of the BAT file to control the flow and to compress everything within a self-extracting EXE using 7-Zip instead of a CAB so I don't need the BAT file to do the extraction. The PPKG runs the EXE, which extracts the PowerShell and SCCM client install and then runs the PowerShell to create the scheduled task and install the SCCM client.

I was just having trouble with the scheduled task not running and wanted to peak at your PS1 to ensure I was going in the right direction. In the end, it was a simple mistake where I forgot to escape the computer name variable, so it was using the name before it's changed to the serial number by the PPKG.

Thanks a lot for your help!

**Comment by ml58158** [comment]
Nice.

I'd be interested in see how your using powershell to run the package.
That's the reason that I released it out to the wild; so i can how other's would improve it.

Any change you can post a copy of your powershell file and how you get it to run in ICD?

Thanks.

**Comment by ml58158** [comment]
FWIW... I get rid of the scheduled task by running the command to force delete during my task sequence.

**Comment by AgetroNairb** [comment]
I posted relevant PS code above. This is what I added to the Deploy-Application.ps1 (see attached: [Deploy-Application.ps1.txt](https://github.com/ml58158/SCCM-Client-Dynamic-Provisioning/files/2507946/Deploy-Application.ps1.txt)) from PSAppDeployToolkit. If you're not familiar with that toolkit, I put the link in the previous post. We've been using the PSAppDeployToolkit as a template for deploying applications with SCCM.

I then used the [7-Zip SDK](https://www.7-zip.org/sdk.html) to zip the files up in a self-extracting EXE. See my attached batch file [7zS2.cmd.txt](https://github.com/ml58158/SCCM-Client-Dynamic-Provisioning/files/2507959/7zS2.cmd.txt) and config file [Config.txt](https://github.com/ml58158/SCCM-Client-Dynamic-Provisioning/files/2507960/Config.txt) for how I created the EXE using the SDK.

I'm also attaching my ICD customization file ([customizations.xml.txt](https://github.com/ml58158/SCCM-Client-Dynamic-Provisioning/files/2507971/customizations.xml.txt)) to view, though, once the EXE is built, it's just a matter of running it. It's pretty light so far since I'm just beginning testing with provisioning packages.

Lastly, for adding the device to a collection via the scheduled task, I'm using web services modeled after ConfigMgrWebService (see link in post above).

I'm fairly new at posting anything to GitHub, so I hope I posted the files correctly. Please let me know if you have any questions.

**Comment by ml58158** [comment]
Awesome.  I appreciate it.

I'll try it out tomorrow and let you know how it goes.

I use the app deploy toolkit all the time for SCCM automation.

**Comment by ml58158** [comment]
BTW.. Where are you using it the process at currently?
Is it just something you are exploring or are you looking at using it in a more wider scale?

**Comment by AgetroNairb** [comment]
Primarily just exploring my options, but also as a possible solution to dip our toes in the pool of using the OEM Win10 bits while we consider going to AutoPilot. I thought it might be a good bridge between the two to get people (techs and users) used to the scenario.

**Comment by ml58158** [comment]
It's a good way to use autopilot without autopilot.

A clear advantage is that my method installs our software in less than 15 mins.
It takes inTune up to 24 hours to deliver software to a user's machine.

If you need assistance or want to consult, let me know.
I'd be glad to get on Skype call .
